<h2>&lt;? Online-PHP::<span class='orange'>About / FAQ</span> ?&gt;</h2>
<div class="right_panel_ad"><? load_view('right_ad'); ?></div>
<div class="about">
    <li>
    <h3>Intro</h3>
    <p><a href="<?=_HTTP_ROOT?>/" title="Homepage">Online-php.com</a> is a <b>free online IDE</b> for editing files on an FTP server where usually all the code is stored.<br>
    This web application uses <a href="http://codemirror.net/" target="_blank">CodeMirror</a> editor module for syntax highlighting and convenient editing.<br><br>
    </p>
    </li>
    
    <li>
    <h3>Purpose</h3>
    <p>
        The application was created for <b>fast, free, simple and convenient read/write access to the files on FTP server</b>.<br>
        Sometimes, for some purposes, the direct FTP access is blocked and there is no conventional way to access the files on the server.
        This is the main reason for this WebApp.
    </p>
    </li>

    <li>
    <h3>FAQ</h3>
    <p><b>1. Is this application secure, and how can I be sure that my passwords won't be stolen?</b></p>
    <p>This web application does not store any private data, code or files on the server, primarilly for security issues. 
    Actually, you cannot really be sure until you see the entire application's code, but honestly, many of 
    my friends and I use this application and me neither want my private data to be found in the internet or stored
    on any PC. <br>
    <u>This web application uses database only for storing <a href="/?page=blog">blog</a> posts and comments</u>.
    There is no registration or login required on the site for the same reasons - I cannot take the responsibility on your private data.
    </p><br>
    <p><b>2. Is the application free?</b></p>
    <p>Yes, the application is absolutely free.</p><br><br>
    </li>
    
    
    <li>
    <a name="upgrade"></a>
    <h3>Upgrade instructions</h3>
    <p><b>1. Is this application secure, and how can I be sure that my passwords won't be stolen?</b></p>
    <p>This web application does not store any private data, code or files on the server, primarilly for security issues. 
    Actually, you cannot really be sure until you see the entire application's code, but honestly, many of 
    my friends and I use this application and me neither want my private data to be found in the internet or stored
    on any PC. <br>
    <u>This web application uses database only for storing <a href="/?page=blog">blog</a> posts and comments</u>.
    There is no registration or login required on the site for the same reasons - I cannot take the responsibility on your private data.
    </p><br>
    <p><b>2. Is the application free?</b></p>
    <p>Yes, the application is absolutely free.</p><br><br>
    </li>
</div>