<div class="source_email_window"><div class="source_email_window_inner">
    <h3>Subscribe to download</h3>
    <p>
        For tracking downloads and keeping you up-to-date,<br/>
        please submit your email for downloading the source code
    </p>
    <form action="<?=_HTTP_ROOT?>/source/subscribe/" method="post" onsubmit="return check_subscribe_form(this);">
        <input type="hidden" name="sec_key" value="<?=uniqid();?>" />
        <input class="input_text" type="text" name="email" maxlength="250" /><br/>
        <label for="subscribe"><input type="checkbox" id="subscribe" name="subscribe" value="1" checked/>Receive updates</label><br/>
        <input class="input_submit" type="submit" value="Subscribe & Download" name="submit" />
        <input class="input_submit" type="button" value="Cancel" onclick="$('.source_email_window').fadeOut();"/>
    </form>
</div></div>
<h2>&lt;? Online-PHP::<span class='orange'>SourceCode</span> ?&gt;</h2>
<div class="right_panel_ad"><? load_view('right_ad'); ?></div>
<ul class="source">
        <li>
            <h3>Open Source</h3>
            <p>
            <ul>
                <li>
                    The application is an <b>OPEN SOURCE</b> project.
                    You can use or modify the source code as you whish, as long as it is not for
                    commercial purpose.<br>
                </li>
                <li>
                    Please send all the changes you made to an email 
                    <a href="mailto:www.online.php@gmail.com">www.online.php@gmail.com</a> (as a ZIP archive)<br>
                </li>
                <li>
                    Please stay up-to-date with the application and do not remove the code lines which perform the update check.
                </li>
		<li>
		    You may also browse the code on code.google.com project hosting service:<br>
		    <a target="_blank" href="https://code.google.com/p/online-php-ide/">https://code.google.com/p/online-php-ide/</a><br />
		    <br>
		    <i><b>svn checkout http://online-php-ide.googlecode.com/svn/trunk/ online-php-ide-read-only</b></i><br><br>
		    I recommend downloading the source code directly from the site (button below), because this
		    is the latest version of the application 
		    (the ZIP is being created on-the-fly, with intervals of a hour - you can see this script in the code)
		    
		</li>
            </ul>
            </p>
        </li>
        <li>
            <h3>Source Features...</h3>
            <p>
            <ul>
                <li>
                    The source code contains all the <b>textual sections</b> (Blog, Snippets, Tutorials, etc),
                    They can be also useful for internal usage for companies or individual use.
                </li>
                <li>
                    The <b>textual sections</b> (Blog, Snippets, etc) use <b>SQLite database</b> (with PDO wrapper).
                    Check if your server support it.
                </li>
                <li>
                    The source code is <b>archived on-the-fly</b>, so the ZIP archive you download is 
                    identical to the code on the server.<br/>
                    You can feel free to use the online version of the application.
                </li>
                <li>
                    The <b>source code contains administration panel</b> for all the textual content.<br>
                    The username and the password are taken from the `users` table from the SQLite database
                    (located in <b>/db</b> directory)
                </li>
            </ul>
            </p>
        </li>
        <li>
            <p class="download_link_wrapper">
                <a class="download_link" href="#" onclick="open_subscribe_window();">Download</a>
            </p>
        </li>
</ul>
