<h2>&lt;? Online-PHP::<span class='orange'>SourceCode</span> ?&gt;</h2>
<div class="right_panel_ad"><? load_view('right_ad'); ?></div>
<ul class="source">
        <li>
            <h3>Open Source</h3>
            <p>
            <ul>
                <li>
                    The application is an <b>OPEN SOURCE</b> project.
                    You can use or modify the source code as you whish, as long as it is not for
                    commercial purpose.<br>
                </li>
                <li>
                    Please send all the changes you made to an email 
                    <a href="mailto:www.online.php@gmail.com">www.online.php@gmail.com</a> (as a ZIP archive)<br>
                    (GitHub project will be opened soon)
                </li>
            </ul>
            </p>
        </li>
        <li>
            <h3>Source Features...</h3>
            <p>
            <ul>
                <li>
                    The source code contains all the <b>textual sections</b> (Blog, Snippets, Tutorials, etc),
                    They can be also useful for internal usage for companies or individual use.
                </li>
                <li>
                    The <b>textual sections</b> (Blog, Snippets, etc) use <b>SQLite database</b> (with PDO wrapper), 
                    so the server should support these.
                </li>
                <li>
                    The source code is <b>archived on-the-fly</b>, so the ZIP archive you download is 
                    identical to the code on the server.
                </li>
                <li>
                    The <b>source code contains administration panel</b> for all the textual content.<br>
                    The username and the password are taken from the `users` table from the SQLite database
                    (located in <b>/db</b> directory)
                </li>
            </ul>
            </p>
        </li>
        <li>
            <p class="download_link_wrapper">
                <a class="download_link" href="<?=_HTTP_ROOT?>/source/download/">Download</a>
            </p>
        </li>
</ul>
